# Generated by Django 5.0.3 on 2024-04-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_author_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(related_name="book", to="books.author"),
        ),
    ]
