# Generated by Django 5.0.3 on 2024-04-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_alter_book_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(default="", upload_to="images"),
        ),
    ]
