# Generated by Django 5.0.3 on 2024-04-03 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("biography", models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                "verbose_name": "Yazar",
                "verbose_name_plural": "Yazarlar",
            },
        ),
        migrations.CreateModel(
            name="Makale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField(blank=True, max_length=1000, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("activate", models.BooleanField(default=True)),
                ("isHome", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gazeteapp.author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Makale",
                "verbose_name_plural": "Makaleler",
                "ordering": ["id"],
            },
        ),
    ]
