# Generated by Django 5.0.3 on 2024-04-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0006_alter_book_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="image",
            field=models.ImageField(default="", upload_to="image"),
        ),
    ]
