# Generated by Django 5.0.3 on 2024-04-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Yazar", "verbose_name_plural": "Yazarlar"},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "Kitap", "verbose_name_plural": "Kitaplar"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Kategori", "verbose_name_plural": "Kategoriler"},
        ),
        migrations.AddField(
            model_name="author",
            name="slug",
            field=models.SlugField(
                blank=True, default=None, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(
                blank=True, default=None, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, default=None, max_length=100, null=True, unique=True
            ),
        ),
    ]
