# Generated by Django 5.0.3 on 2024-04-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gazeteapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="image",
            field=models.ImageField(default="", upload_to="img"),
        ),
        migrations.AddField(
            model_name="makale",
            name="image",
            field=models.ImageField(default="", upload_to="img"),
        ),
    ]
